POST {{auth}}/users/sign-up
Content-Type: application/json

{
  "provider": "GOOGLE",
  "providerAccessToken": "ya29.a0AfH6SMDqTyXjkpxXFtQ9PQ3rDNe04dyExRJFpbzAETE9kATL6quNdq3weVozsLC5s7JHruBe7NRU9_2ZwRV2iKLDwK_oUU5wZSrIe45OI6945dfYx-_-91GpwSRQc7D8PV83G3DcADf_BVGyoWBy16JKLJ4TsnZHRX8m",
  "nickname": "김명재"
}

###
POST {{auth}}/users/sign-in
Content-Type: application/json

{
  "provider": "GOOGLE",
  "providerAccessToken": "ya29.a0AfH6SMDqTyXjkpxXFtQ9PQ3rDNe04dyExRJFpbzAETE9kATL6quNdq3weVozsLC5s7JHruBe7NRU9_2ZwRV2iKLDwK_oUU5wZSrIe45OI6945dfYx-_-91GpwSRQc7D8PV83G3DcADf_BVGyoWBy16JKLJ4TsnZHRX8m"
}

###
POST {{auth}}/users/sign-out
Content-Type: application/json

{
  "refresh_token": "baedc3bd-6a6f-4a63-b0b8-b590260b4985"
}

###
POST {{auth}}/users/token-refresh
Content-Type: application/json

{
  "refresh_token": "3f103e78-ddda-4d75-9040-3e0ae6aa440c"
}

###
POST {{auth}}/oauth/check_token
Authorization: Basic Zmlyc3QtY2xpZW50Om5vb25ld2lsbGV2ZXJndWVzcw== # first-client:noonewilleverguess
Content-Type: application/x-www-form-urlencoded

token=5cd89de9-926d-4752-8559-bb23515c1bd7

###


